data_path: ./   # 数据存放路径

# 关键帧
key_frame_distance: 2.0 # 关键帧距离

map:
  ori_longitude_: 121.439743
  ori_latitude_: 31.0263253
  ori_height_: 15.866


lidar2imu_: [ 1, 0, 0,0,
                         0, 1,0,0, 
                         0, 0,1,0,
                         0,0,0,1]

