data_path: ./   # 数据存放路径
map_path: ./   # 地图存放路径,本电脑或者mdc上的路径
# map_path: /media/lirui/LENOVO_USB_HDD/Haibo_dataset/gridmap   # 地图存放路径,本电脑或者mdc上的路径

# 之所以要提供no_filter（即不滤波）模式，是因为闭环检测对计算时间要求没那么高，而点云越稠密，精度就越高，所以滤波与否都有道理
map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter

global_map_filter: ground_filter # 选择地面滤除的滤波方法，目前支持：pcl::ransac、pcl::ransac_with_normal
# global_map_filter: ground_filter_with_normal
# global_map_filter: ground_filter_with_grid

global_map_outlier_filter: outlier_filter
post_map_filter: post_ground_filter 
global_map_rasterization: elevation_rasterization
# 各配置选项对应参数
## 地面滤除相关参数
ground_filter:
    opt_coeff : 1
    dist_threshold : 0.45
    max_iter : 1000
# 去除outlier点
outlier_filter:
    filter_radius : 1.5
    filter_count : 8
# 利用法向量做地面滤除的相关参数
ground_filter_with_normal:
    opt_coeff : 1
    dist_threshold : 0.45
    max_iter : 1000
# 利用栅格做地面滤除的相关参数
ground_filter_with_grid:
    count_threshold : 3
    height_threshold : 0.2
    map_resolution: 0.3
#postmap地面滤除相关参数
post_ground_filter:
    opt_coeff : 1
    dist_threshold : 0.45
    max_iter : 1000
## 滤波相关参数
voxel_filter:
    map:
        leaf_size: [0.3, 0.3, 0.3]
    scan:
        leaf_size: [0.3, 0.3, 0.3]
#生成栅格的相关参数
elevation_rasterization:
    count_threshold : 7
    height_threshold : 0.4
    inflation_map_x : 150
    inflation_map_y : 150
    map_resolution: 1
    outliers_dis: 25
    bool_visual: false



