data_path: ./   # 数据存放路径
map_path: ./   # 地图存放路径,本电脑或者mdc上的路径
# map_path: /media/lirui/LENOVO_USB_HDD/Haibo_dataset/gridmap   # 地图存放路径,本电脑或者mdc上的路径


# 之所以要提供no_filter（即不滤波）模式，是因为闭环检测对计算时间要求没那么高，而点云越稠密，精度就越高，所以滤波与否都有道理
map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter
global_map_filter: ground_filter 
post_map_filter: post_ground_filter 
global_map_rasterization: elevation_rasterization
# 各配置选项对应参数
## 地面滤除相关参数
ground_filter:
    opt_coeff : 1
    dist_threshold : 0.6
    max_iter : 1000
#postmap地面滤除相关参数
post_ground_filter:
    opt_coeff : 1
    dist_threshold : 0.6
    max_iter : 1000
## 滤波相关参数
voxel_filter:
    map:
        leaf_size: [0.3, 0.3, 0.3]
    scan:
        leaf_size: [0.3, 0.3, 0.3]
#生成栅格的相关参数
elevation_rasterization:
    count_threshold : 7
    height_threshold : 0.4
    inflation_map_x : 150
    inflation_map_y : 150
    map_resolution: 1



