data_path: ./   # 数据存放路径
map_path: ./   # 地图存放路径,本电脑或者mdc上的路径
# map_path: /disk3/ConchFile/gridmap   # 地图存放路径,本电脑或者mdc上的路径

#滤波参数
# 全局地图
global_map_filter: voxel_filter # 选择全局地图点云滤波方法，目前支持：voxel_filter

# global_map_ground_filter: ground_filter
global_map_ground_filter: ground_filter_with_normal
# global_map_ground_filter: ground_filter_with_grid

global_map_ground_grid_filter: ground_filter_with_grid

# 局部地图
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗小地图点云滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

#生成栅格地图
global_map_rasterization: elevation_rasterization

# 各配置选项对应参数
## 滤波相关参数
voxel_filter:
    global_map:
        leaf_size: [0.5, 0.5, 0.5]
    local_map:
        leaf_size: [0.5, 0.5, 0.5]
    frame:
        leaf_size: [0.5, 0.5, 0.5]

ground_filter:
    opt_coeff : 1
    dist_threshold : 0.35
    max_iter : 1000
# 去除outlier点
outlier_filter:
    filter_radius : 1.5
    filter_count : 8
# 利用法向量做地面滤除的相关参数 
ground_filter_with_normal:
    opt_coeff : 1
    dist_threshold : 0.35
    max_iter : 1000
# 利用栅格做地面滤除的相关参数
ground_filter_with_grid:
    count_threshold : 2
    height_threshold : 0.03
    map_resolution: 2.5

#生成栅格的相关参数
elevation_rasterization:
    count_threshold : 5
    height_threshold : 0.25
    inflation_map_x : 150
    inflation_map_y : 150
    map_resolution: 1
    outliers_dis: 10
    bool_visual: true


